TALISMAN Log file

2018/06/15-04:40:28 : Log start: EVENT

!!! **************************************************
2018/06/15-04:40:28 : !!! Start test, script file: tst-exc-07.script

// Script:    Tst-main-07.script
// Author:    Arndt von Staa
// Date:      02/dec/2011
// Purpose:   Test basic functionality
// Test throw, do not catch due to incorrect recovery command
//
// ==========>>> Must stop with 4 errors and disaster
//
     12 == Declarations
     24 == Test incorrect exception catcher

>>> 1    Line 25  Tester caught a program exception, context 0 >>
--- EXC: PROGRAM: Thrown while testing
        Exception thrown in Line: 837  File: ..\sources\tst_exc.cpp

>>> 2    Line 26  Command is not a program exception catcher:  =ExceptionSystem
>>> 3    Line 26  Program exception catch command does not recover:  =ExceptionSystem

######  Unexpected program exception !!!!!

    4    Line 26  vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv 
>>> 5    Line 26  Test crash: Program will be cancelled.
 


>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


>>>DISASTER: Test has been cancelled prior to ending !!!

      At Line: 250  In module: ..\sources\gnrctest.cpp

>>>DISASTER: Starting roll back.


>>>DISASTER: Roll back completed. Program will be canceled now !!!


>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


