TALISMAN Log file

2018/06/15-04:40:28 : Log start: EVENT

!!! **************************************************
2018/06/15-04:40:28 : !!! Start test, script file: tst-exc-03.script

// Script:    Tst-main-03.script
// Author:    Arndt von Staa
// Date:      02/dec/2011
// Purpose:   Test basic functionality
// Test throw, incorrectly catch due to exception type error
//
// ==========>>> Must stop with 5 errors and disaster
//
     12 == Declarations
     27 == Test incorrect exception catcher, wrong type

>>> 1    Line 28  Tester caught a program exception, context 0 >>
--- EXC: PROGRAM: Thrown while testing
        Exception thrown in Line: 837  File: ..\sources\tst_exc.cpp

>>> 2    Line 29  Incorrect exception type  Is 5  Should be 3
>>> 3    Line 29  Program exception catch command does not recover:  =ExceptionProgram   typeError    tstMessage  'c'

######  Unexpected program exception !!!!!

    4    Line 29  vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv 
>>> 5    Line 29  Test crash: Program will be cancelled.
 


>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


>>>DISASTER: Test has been cancelled prior to ending !!!

      At Line: 250  In module: ..\sources\gnrctest.cpp

>>>DISASTER: Starting roll back.


>>>DISASTER: Roll back completed. Program will be canceled now !!!


>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


