TALISMAN Log file

2018/06/15-04:40:28 : Log start: EVENT

!!! **************************************************
2018/06/15-04:40:28 : !!! Start test, script file: tst-exc-05.script

// Script:    Tst-main-05.script
// Author:    Arndt von Staa
// Date:      02/dec/2011
// Purpose:   Test basic functionality
// Test throw, with illegal recovery command
//
// ==========>>> Must stop with 5 errors and disaster
//
     12 == Declarations
     26 == Test incorrect command after a caught exception

>>> 1    Line 27  Tester caught a program exception, context 0 >>
--- EXC: USAGE: Thrown while testing
        Exception thrown in Line: 834  File: ..\sources\tst_exc.cpp

>>> 2    Line 28  Command is not a program exception catcher:  =something
>>> 3    Line 28  Program exception catch command does not recover:  =something

######  Unexpected program exception !!!!!

    4    Line 28  vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv 
>>> 5    Line 28  Test crash: Program will be cancelled.
 


>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


>>>DISASTER: Test has been cancelled prior to ending !!!

      At Line: 250  In module: ..\sources\gnrctest.cpp

>>>DISASTER: Starting roll back.


>>>DISASTER: Roll back completed. Program will be canceled now !!!


>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


